### ISSUE TITLE
Unable to reproduce the inference on my images from pre-trained models

### ISSUE THREAD

**Issue by Gourav2K** [chenjun2hao/DDRNet.pytorch#8]
I am trying to reproduce the model results on my own dataset from the pre-trained models on cityscapes but tools/eval.py is throwing errors each time I am trying and fixing the details.
Can you just give me a gist of steps that I would need to take in order to get inference on my images from the pretrained model of ddrnet23_slim?

**Comment by chenjun2hao** [comment]
@Gourav2K , you can debug with pycharm. or you can use `test.py` for test on your own dataset.

**Comment by Tetsujinfr** [comment]
hi

test.py does not seems to be much related to an inference file. eval.py is closer in my view but maybe I am missing something here? 
btw what is demo.py about? it does not seems to be an inference demo.
thanks

**Comment by Gourav2K** [comment]
Exactly, I am facing the exact same issues. test.py contains commented-out statements and eval.py does not seem to generate inferences.
